# Generated by Django 4.2.1 on 2023-06-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
            ],
        ),
        migrations.CreateModel(
            name='Services_rendered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=70, verbose_name='SERVICES')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('appointment_date', models.DateTimeField(verbose_name='Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.registered_doctors')),
                ('service_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.services_rendered')),
            ],
        ),
    ]
