# Generated by Django 4.2.1 on 2023-06-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_doctors',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
