# Generated by Django 4.2.1 on 2023-06-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_second_name_registered_doctors_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registered_doctors',
            new_name='Registered_doctor',
        ),
    ]
