# Generated by Django 4.2.1 on 2023-06-19 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_registered_doctors_registered_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment_db',
            old_name='service_db',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='appointment_db',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 22, 14, 44, 648418), verbose_name='Date'),
        ),
    ]
