# Generated by Django 4.2.1 on 2023-06-20 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_service_db_appointment_db_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_rendered',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.registered_doctor'),
        ),
        migrations.AlterField(
            model_name='appointment_db',
            name='appointment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 12, 8, 7, 380410), verbose_name='Date'),
        ),
    ]
